### PR TITLE
add unwrap

### LINKED ISSUE #11: A unwrap function for arrays in ObjectPools.jl
A reminder for us to take care of the possibly unwanted behavior in using `parent(A)` to unwrap `FlexArray` or `FlexArrayCache` into `PtrArray`.

### PR DESCRIPTION
**Pull request by CheukHinHoJerry**

### CODE REVIEW

**Comment by cortner** [comment]
I think this might be done actually? Just need to add some brief documentation of `unwrap` to the README?

**Comment by CheukHinHoJerry** [comment]
Yes I think so. And may remove the `parent` test in the testing script and move to somewhere to check for deprecate?

**Comment by cortner** [comment]
would you mind adding a paragraph to the Readme then I'll merge?

**Comment by CheukHinHoJerry** [comment]
Should be ready to merge, sorry for making so many small commits. Could you please take a final look?

**Pull request merged**
